==={}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[100]	training's l2: 3.16016e+06
time:48.511246375739574 	R2: 0.8393	RMSE: 1804
==={'n_estimators': 512}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[512]	training's l2: 2.7123e+06
time:221.48621564731002 	R2: 0.8475	RMSE: 1757
==={'learning_rate': 0.25}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[512]	training's l2: 2.7123e+06
time:49.60353308171034 	R2: 0.8371	RMSE: 1816
==={'n_estimators': 512, 'learning_rate': 0.25}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[512]	training's l2: 2.6325e+06
time:236.20703814923763 	R2: 0.8363	RMSE: 1821
==={'max_depth': 64, 'num_leaves': 1027}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
----------------------------------------------------------{'objective':'l2','subsample':.2,'subsample_freq':4}------------------------------------------------------------
==={}====
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[100]	training's l2: 3.17792e+06
time:7.984205394983292 	R2: 0.8392	RMSE: 1805
==={'n_estimators': 512}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[512]	training's l2: 2.75783e+06
time:34.305661141872406 	R2: 0.8462	RMSE: 1765
==={'learning_rate': 0.25}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[512]	training's l2: 2.75783e+06
time:6.791852876543999 	R2: 0.8362	RMSE: 1821
==={'n_estimators': 512, 'learning_rate': 0.25}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[512]	training's l2: 2.65931e+06
time:34.09876178577542 	R2: 0.8342	RMSE: 1832
==={'max_depth': 64, 'num_leaves': 1027}====

/opt/conda/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')

Did not meet early stopping. Best iteration is:
[100]	training's l2: 2.16396e+06
time:61.51865614950657 	R2: 0.8511	RMSE: 1736
